# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Art < Formula
  desc "Argonaut makes DevOps Simple"
  homepage "https://argonaut.dev/"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/argonautdev/public/releases/download/v0.7.1/art_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f6598af762b4cc1b4c4e5efa6ccec0e4882360f1b41ceedb0f0d286bb3e59741"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/argonautdev/public/releases/download/v0.7.1/art_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9de2d1f8577f1637898e147f0769e3a6e92b527ccccca5880b347363c89efe0f"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/argonautdev/public/releases/download/v0.7.1/art_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a2241a8550a3f7ed84b845eb7b538b7508a3bddf34edcafe13ada5d6e624206e"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/argonautdev/public/releases/download/v0.7.1/art_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cb7bb705e5c654501072ee241e5b42ce4e814cb3aa25e2a257d6f5b18c4d2e4f"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
  end

  test do
    system "#{bin}/art -v"
  end
end
