# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Art < Formula
  desc "Argonaut makes DevOps Simple"
  homepage "https://argonaut.dev/"
  version "0.4.6-alpha.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/argonautdev/public/releases/download/v0.4.6-alpha.4/art_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "43b2651061e1b7243b7c63accb6ed5cadea1d4fd86993722957ce03ca3a6d529"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/argonautdev/public/releases/download/v0.4.6-alpha.4/art_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cb17493ac37aaf33a7fc2bf7b12d98eb2be60dbb69b6d0637576de9494139943"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/argonautdev/public/releases/download/v0.4.6-alpha.4/art_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "bc95e7449b992093bb64ee771f128ebc2fbc1c4984bd733e94272e2b2e955f0c"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/argonautdev/public/releases/download/v0.4.6-alpha.4/art_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4c65c2810d472bff24d47372bd9dde105c519da67d468123cf35f0b2a9859b0f"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
  end

  test do
    system "#{bin}/art -v"
  end
end
