# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Art < Formula
  desc "Argonaut makes DevOps Simple"
  homepage "https://argonaut.dev/"
  version "0.14.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/argonautdev/public/releases/download/v0.14.5/art_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "499eba67e97ea4ccad045617e0e715736e7bad0f19569ade5430b9e81a6a4da8"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/argonautdev/public/releases/download/v0.14.5/art_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "afc8dcc09c3034f5860d8ed0d94e13c9db0db9e59e39f26a770a83d17e1325f1"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/argonautdev/public/releases/download/v0.14.5/art_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "293580ecd5c781c99fa946a11f0ec78c4cc5c61f318e913194d09b54c5ea1be9"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/argonautdev/public/releases/download/v0.14.5/art_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "2b4b41c8883958d674b4969149308c9792d2539d94080c6847c9528b5b06381d"

      def install
        bin.install "art"
        bash_completion.install "completions/art.bash" => "art"
        zsh_completion.install "completions/art.zsh" => "_art"
        fish_completion.install "completions/art.fish"
      end
    end
  end

  test do
    system "#{bin}/art -v"
  end
end
